version: '3'

services:
  # MySQL Database Service
  database:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: florajet
      MYSQL_USER: user
      MYSQL_PASSWORD: root
    ports:
    # Maps port 3306 on the host to port 3306 on the MySQL container
      - "3306:3306"  

  phpmyadmin:
    depends_on:
      - database
    image: phpmyadmin
    restart: always
    ports:
      - 8081:80
    environment:
      PMA_HOST: database

volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###